move jwt from query string to headers
sumoheavy/jira-ruby pull request #411
Opened 2023-09-06 16:16 UTC by aleksei-okatiev

Atlassian deprecated and removed JWT as a query param, now it should be in a header.
https://developer.atlassian.com/changelog/#CHANGE-995

2023-09-25 14:30 UTC, adam-mazur-gat requested changes

2023-09-25 14:30 UTC, adam-mazur-gat commented on lib/jira/jwt_client.rb
>      class JwtUriBuilder
Is it used somewhere outside of this file?
The only usage in this file is removed `JwtUriBuilder`

2023-09-25 14:30 UTC, adam-mazur-gat commented on lib/jira/jwt_client.rb
> +    class JwtBuilder
If `build_jwt` is the only user of jwt building do we need a class for this? Can we just 

```ruby
 claim = Atlassian::Jwt.build_claims \
          issuer,
          request_url,
          http_method.to_s,
          site,
          (Time.now - 60).to_i,
          (Time.now + 86_400).to_i

        JWT.encode claim, shared_secret
```

in the `build_jwt`?

2023-09-25 14:34 UTC, gat-developer commented on lib/jira/jwt_client.rb
>      def make_multipart_request(url, data, headers = {})
Should we do the same changes as for `make_request` here?

2024-04-01 22:06 UTC, bobbrodie commented
Closing as dupe of #412

2024-04-01 22:06 UTC, closed without merging